[features]
seeds = false
[programs.localnet]
p0001 = "2DhNq3n17844BkNDngD9iDgMPwLYqUxo4VcnWjLUry6E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/tiny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
